### ISSUE TITLE
Migration from Hilt to Koin.

### ISSUE THREAD

**Issue by Unique0o** [skydoves/pokedex-compose#35]
While hilt creates an unnecessary burden on the codebase at compile time and run-time when utilizing reflection. I would suggest replacing Hilt with Koin. Koin is very lightweight and based on Kotlin's core capabilities. It utilize extension functions thus providing outstanding performance eventually avoiding reflection and annotations processing.

**Comment by skydoves** [comment]
I know someone prefer Koin rather than Hilt, but in most case, Hilt used to have a better performance in large projects. Check out the discussion below: https://www.reddit.com/r/androiddev/comments/8ch4cg/dagger2_vs_koin_for_dependency_injection/

On the other hand, I'm planning to use Koin for my future KMP project for Pokedex :)
